### ISSUE TITLE
Connect database with project

### ISSUE THREAD

**Issue by ninagern** [void-tech-um/open-course#11]
Test that database properly shows user information in a testing environment
- run ./bin/ocRun
- check that database information is populating the HTML pages
- this can be completed once #10 is finished

**Comment by jennweir** [comment]
This is still currently in progress. We have faced some issues with getting the flask code to render contents from the database but it is likely a silly flask error.

**Comment by jennweir** [comment]
Connection to AWS and database is actively working. Closing issue.
