### ISSUE TITLE
Setup AWS instance

### ISSUE THREAD

**Issue by ninagern** [void-tech-um/open-course#8]
Setup AWS ECS instance. Amazon EC2 provides the ability to place instances in multiple locations. EC2 supports virtual machines and cloud computing environments. For the purposes of this project we'll use EC2 instances for both database and web application. Developers are expected to complete this configuration and close issue once PR is finished.

**Comment by jennweir** [comment]
EC2 instance was created at the Wednesday meeting on 1/17.
